export const questions = [
  { question: "What's the capital of France?", options: ["Paris", "Rome", "Madrid", "Berlin"], answer: 0 },
  { question: "Which planet is known as the Red Planet?", options: ["Earth", "Saturn", "Mars", "Venus"], answer: 2 },
  { question: "Which continent is the Sahara Desert in?", options: ["Asia", "Africa", "Australia", "South America"], answer: 1 },
  { question: "What is the smallest country in the world?", options: ["Vatican City", "Monaco", "San Marino", "Liechtenstein"], answer: 0 },
  { question: "Which ocean is the deepest?", options: ["Atlantic", "Arctic", "Indian", "Pacific"], answer: 3 },
  { question: "Which country has the most people?", options: ["India", "USA", "China", "Brazil"], answer: 2 },
  { question: "Where is Mount Everest located?", options: ["India", "Nepal", "China", "Bhutan"], answer: 1 },
  { question: "What's the capital of Japan?", options: ["Beijing", "Kyoto", "Seoul", "Tokyo"], answer: 3 },
  { question: "Which is the longest river?", options: ["Amazon", "Nile", "Yangtze", "Mississippi"], answer: 1 },
  { question: "Which is the largest desert?", options: ["Gobi", "Kalahari", "Sahara", "Arctic"], answer: 2 },
  { question: "Which country is known as the Land of the Rising Sun?", options: ["China", "South Korea", "Japan", "Thailand"], answer: 2 },
  { question: "What is the capital of Canada?", options: ["Toronto", "Vancouver", "Ottawa", "Montreal"], answer: 2 },
  { question: "Which country has the most islands?", options: ["Indonesia", "Philippines", "Sweden", "Greece"], answer: 2 },
  { question: "Which US state is the Grand Canyon in?", options: ["Nevada", "Utah", "Arizona", "Colorado"], answer: 2 },
  { question: "What's the capital of Australia?", options: ["Sydney", "Melbourne", "Canberra", "Brisbane"], answer: 2 },
  { question: "Which African country has pyramids?", options: ["Egypt", "Sudan", "Morocco", "Algeria"], answer: 1 },
  { question: "What's the capital of Italy?", options: ["Venice", "Rome", "Milan", "Naples"], answer: 1 },
  { question: "What language is spoken in Brazil?", options: ["Spanish", "Portuguese", "English", "French"], answer: 1 },
  { question: "What is the capital of Russia?", options: ["Moscow", "St. Petersburg", "Kiev", "Minsk"], answer: 0 },
  { question: "Which country does Greenland belong to?", options: ["USA", "Canada", "Denmark", "Norway"], answer: 2 },
  { question: "Which is the largest island?", options: ["Australia", "Greenland", "New Guinea", "Borneo"], answer: 1 },
  { question: "Where is the Taj Mahal?", options: ["Delhi", "Agra", "Jaipur", "Mumbai"], answer: 1 },
  { question: "What's the capital of Argentina?", options: ["Lima", "Bogotá", "Buenos Aires", "Santiago"], answer: 2 },
  { question: "Which country has the city of Istanbul?", options: ["Greece", "Turkey", "Cyprus", "Bulgaria"], answer: 1 },
  { question: "What is the capital of South Korea?", options: ["Busan", "Incheon", "Seoul", "Daegu"], answer: 2 },
  { question: "Which city hosted the 2016 Olympics?", options: ["Tokyo", "London", "Rio", "Beijing"], answer: 2 },
  { question: "Which continent is the Amazon rainforest in?", options: ["Africa", "Asia", "South America", "Australia"], answer: 2 },
  { question: "What is the capital of Spain?", options: ["Barcelona", "Madrid", "Seville", "Valencia"], answer: 1 },
  { question: "Where is the Great Barrier Reef?", options: ["Thailand", "Australia", "Indonesia", "Philippines"], answer: 1 },
  { question: "Which city is the Statue of Liberty in?", options: ["Los Angeles", "New York", "Chicago", "Boston"], answer: 1 },
  { question: "Where is the Eiffel Tower?", options: ["Rome", "Paris", "Berlin", "London"], answer: 1 },
  { question: "What's the capital of Germany?", options: ["Munich", "Berlin", "Frankfurt", "Hamburg"], answer: 1 },
  { question: "What is the currency of Japan?", options: ["Won", "Yen", "Dollar", "Ruble"], answer: 1 },
  { question: "What's the capital of Mexico?", options: ["Cancún", "Monterrey", "Mexico City", "Guadalajara"], answer: 2 },
  { question: "Which country borders both India and China?", options: ["Nepal", "Myanmar", "Pakistan", "Bangladesh"], answer: 0 },
  { question: "Which city is known for Big Ben?", options: ["Dublin", "Edinburgh", "London", "Manchester"], answer: 2 },
  { question: "Which country is shaped like a boot?", options: ["Spain", "Portugal", "Greece", "Italy"], answer: 3 },
  { question: "What is the capital of Thailand?", options: ["Bangkok", "Phuket", "Chiang Mai", "Pattaya"], answer: 0 },
  { question: "Which African country starts with Z?", options: ["Zambia", "Zimbabwe", "Zanzibar", "Zaire"], answer: 0 },
  { question: "What's the capital of the USA?", options: ["New York", "Washington, D.C.", "Chicago", "Los Angeles"], answer: 1 },
  { question: "Where is the Leaning Tower of Pisa?", options: ["Rome", "Pisa", "Venice", "Florence"], answer: 1 },
  { question: "Which mountain range is in South America?", options: ["Rockies", "Andes", "Himalayas", "Alps"], answer: 1 },
  { question: "Where is the Colosseum?", options: ["Athens", "Rome", "Istanbul", "Naples"], answer: 1 },
  { question: "Which country has a maple leaf on its flag?", options: ["USA", "Canada", "UK", "Switzerland"], answer: 1 },
  { question: "What is the capital of Indonesia?", options: ["Bali", "Jakarta", "Surabaya", "Medan"], answer: 1 },
  { question: "Which country is famous for tulips and canals?", options: ["Belgium", "Switzerland", "Netherlands", "France"], answer: 2 },
  { question: "Where is the Kremlin?", options: ["Moscow", "Kiev", "Warsaw", "St. Petersburg"], answer: 0 },
  { question: "Which country has a dragon on its flag?", options: ["Bhutan", "China", "Nepal", "Vietnam"], answer: 0 },
  { question: "Which city is famous for the Opera House?", options: ["Melbourne", "Perth", "Sydney", "Brisbane"], answer: 2 },
  { question: "What is the capital of Egypt?", options: ["Alexandria", "Cairo", "Luxor", "Aswan"], answer: 1 },
  { question: "Which country is famous for the Machu Picchu?", options: ["Chile", "Peru", "Ecuador", "Bolivia"], answer: 1 },
  { question: "What is the capital of India?", options: ["Mumbai", "New Delhi", "Kolkata", "Chennai"], answer: 1 },
  { question: "Which country has the most time zones?", options: ["Russia", "USA", "China", "Canada"], answer: 0 },
  { question: "What is the capital of Norway?", options: ["Bergen", "Oslo", "Trondheim", "Stavanger"], answer: 1 },
  { question: "Which country is known for the Great Wall?", options: ["Japan", "China", "Korea", "Mongolia"], answer: 1 },
  { question: "What is the capital of Chile?", options: ["Valparaíso", "Santiago", "Concepción", "Antofagasta"], answer: 1 },
  { question: "Which African country is landlocked and starts with 'B'?", options: ["Botswana", "Benin", "Burkina Faso", "Burundi"], answer: 0 },
  { question: "What is the capital of Vietnam?", options: ["Ho Chi Minh City", "Hanoi", "Da Nang", "Hue"], answer: 1 },
  { question: "Which country is home to Angkor Wat?", options: ["Thailand", "Cambodia", "Laos", "Vietnam"], answer: 1 },
  { question: "What is the capital of Turkey?", options: ["Istanbul", "Ankara", "Izmir", "Antalya"], answer: 1 },
  { question: "Which country has the Statue of Christ the Redeemer?", options: ["Argentina", "Brazil", "Chile", "Colombia"], answer: 1 },
  { question: "What is the capital of Kenya?", options: ["Mombasa", "Nairobi", "Kisumu", "Nakuru"], answer: 1 },
  { question: "Which country is famous for fjords?", options: ["Sweden", "Norway", "Finland", "Denmark"], answer: 1 },
  { question: "What is the capital of Poland?", options: ["Krakow", "Warsaw", "Gdansk", "Wroclaw"], answer: 1 },
  { question: "Which country has the most volcanoes?", options: ["Japan", "Indonesia", "Philippines", "Chile"], answer: 1 },
  { question: "What is the capital of Portugal?", options: ["Porto", "Lisbon", "Braga", "Coimbra"], answer: 1 },
  { question: "Which country is known as the Pearl of Africa?", options: ["Kenya", "Uganda", "Tanzania", "Rwanda"], answer: 1 },
  { question: "What is the capital of Greece?", options: ["Thessaloniki", "Athens", "Patras", "Heraklion"], answer: 1 },
  { question: "Which country has the most natural lakes?", options: ["Finland", "Canada", "Sweden", "Russia"], answer: 1 },
  { question: "What is the capital of Sweden?", options: ["Gothenburg", "Stockholm", "Malmö", "Uppsala"], answer: 1 },
  { question: "Which country is home to the ancient city of Petra?", options: ["Egypt", "Jordan", "Syria", "Lebanon"], answer: 1 },
  { question: "What is the capital of Morocco?", options: ["Casablanca", "Rabat", "Marrakech", "Fez"], answer: 1 },
  { question: "Which country has the most pyramids?", options: ["Egypt", "Sudan", "Mexico", "Peru"], answer: 1 },
  { question: "What is the capital of Iran?", options: ["Isfahan", "Tehran", "Shiraz", "Tabriz"], answer: 1 },
  { question: "Which country is known for its safaris in the Serengeti?", options: ["Kenya", "Tanzania", "Uganda", "Botswana"], answer: 1 },
  { question: "What is the capital of Ireland?", options: ["Cork", "Dublin", "Galway", "Limerick"], answer: 1 },
  { question: "Which country has the most UNESCO World Heritage Sites?", options: ["France", "Italy", "Spain", "Germany"], answer: 1 },
  { question: "What is the capital of Saudi Arabia?", options: ["Jeddah", "Riyadh", "Mecca", "Medina"], answer: 1 },
  { question: "Which country is famous for its chocolate and watches?", options: ["Austria", "Switzerland", "Belgium", "Germany"], answer: 1 },
  { question: "What is the capital of Finland?", options: ["Tampere", "Helsinki", "Turku", "Oulu"], answer: 1 },
  { question: "Which country has the city of Timbuktu?", options: ["Niger", "Mali", "Chad", "Mauritania"], answer: 1 },
  { question: "What is the capital of New Zealand?", options: ["Auckland", "Wellington", "Christchurch", "Hamilton"], answer: 1 },
  { question: "Which country is known for its tango dance?", options: ["Brazil", "Argentina", "Chile", "Uruguay"], answer: 1 },
  { question: "What is the capital of Bangladesh?", options: ["Chittagong", "Dhaka", "Sylhet", "Khulna"], answer: 1 },
  { question: "Which country has the most pandas?", options: ["India", "China", "Nepal", "Myanmar"], answer: 1 },
  { question: "What is the capital of Israel?", options: ["Tel Aviv", "Jerusalem", "Haifa", "Be'er Sheva"], answer: 1 },
  { question: "Which country is famous for its maple syrup?", options: ["USA", "Canada", "Norway", "Sweden"], answer: 1 },
  { question: "What is the capital of Malaysia?", options: ["Penang", "Kuala Lumpur", "Johor Bahru", "Kota Kinabalu"], answer: 1 },
  { question: "Which country has the most castles?", options: ["France", "Germany", "UK", "Ireland"], answer: 1 },
  { question: "What is the capital of Denmark?", options: ["Aarhus", "Copenhagen", "Odense", "Aalborg"], answer: 1 },
  { question: "Which country is known for its geysers and Northern Lights?", options: ["Norway", "Iceland", "Greenland", "Finland"], answer: 1 },
  { question: "What is the capital of South Africa?", options: ["Johannesburg", "Cape Town", "Pretoria", "Durban"], answer: 2 },
  { question: "Which country has the most coral reefs?", options: ["Philippines", "Australia", "Indonesia", "Maldives"], answer: 2 },
  { question: "What is the capital of Austria?", options: ["Salzburg", "Vienna", "Innsbruck", "Graz"], answer: 1 },
  { question: "Which country is famous for its windmills?", options: ["Belgium", "Netherlands", "Denmark", "Germany"], answer: 1 },
  { question: "What is the capital of Belgium?", options: ["Antwerp", "Brussels", "Ghent", "Bruges"], answer: 1 },
  { question: "Which country has the most coffee production?", options: ["Colombia", "Brazil", "Ethiopia", "Vietnam"], answer: 1 },
  { question: "What is the capital of Philippines?", options: ["Cebu", "Manila", "Davao", "Quezon City"], answer: 1 },
  { question: "Which country is known for its kangaroos?", options: ["New Zealand", "Australia", "Papua New Guinea", "Indonesia"], answer: 1 },
  { question: "What is the capital of Czech Republic?", options: ["Brno", "Prague", "Ostrava", "Plzen"], answer: 1 },
  { question: "Which country has the most active volcanoes?", options: ["Japan", "Indonesia", "Chile", "Philippines"], answer: 1 },
  { question: "What is the capital of Ukraine?", options: ["Kharkiv", "Kiev", "Odesa", "Dnipro"], answer: 1 },
  { question: "Which country is famous for its cigars?", options: ["Dominican Republic", "Cuba", "Nicaragua", "Honduras"], answer: 1 },
  { question: "What is the capital of Hungary?", options: ["Debrecen", "Budapest", "Szeged", "Pécs"], answer: 1 },
  { question: "Which country has the most beaches?", options: ["Australia", "Philippines", "Indonesia", "Greece"], answer: 2 },
  { question: "What is the capital of Romania?", options: ["Cluj-Napoca", "Bucharest", "Timișoara", "Iași"], answer: 1 },
  { question: "Which country is known for its lemurs?", options: ["Kenya", "Madagascar", "Tanzania", "Mozambique"], answer: 1 },
  { question: "What is the capital of Croatia?", options: ["Split", "Zagreb", "Dubrovnik", "Rijeka"], answer: 1 },
  { question: "Which country has the most reindeer?", options: ["Finland", "Norway", "Russia", "Sweden"], answer: 2 },
  { question: "What is the capital of Sri Lanka?", options: ["Kandy", "Colombo", "Galle", "Jaffna"], answer: 1 },
  { question: "Which country is famous for its tulip fields?", options: ["Belgium", "Netherlands", "Germany", "Denmark"], answer: 1 },
  { question: "What is the capital of Bulgaria?", options: ["Plovdiv", "Sofia", "Varna", "Burgas"], answer: 1 },
  { question: "Which country has the most elephants?", options: ["Kenya", "Botswana", "Tanzania", "South Africa"], answer: 1 },
  { question: "What is the capital of Lithuania?", options: ["Kaunas", "Vilnius", "Klaipėda", "Šiauliai"], answer: 1 },
  { question: "Which country is known for its wine regions?", options: ["Italy", "France", "Spain", "Portugal"], answer: 1 },
  { question: "What is the capital of Latvia?", options: ["Daugavpils", "Riga", "Liepāja", "Jelgava"], answer: 1 },
  { question: "Which country has the most penguins?", options: ["Chile", "Antarctica", "Argentina", "South Africa"], answer: 1 },
  { question: "What is the capital of Estonia?", options: ["Tartu", "Tallinn", "Narva", "Pärnu"], answer: 1 },
  { question: "Which country is famous for its spices?", options: ["Thailand", "India", "Indonesia", "Mexico"], answer: 1 },
  { question: "What is the capital of Slovenia?", options: ["Maribor", "Ljubljana", "Celje", "Kranj"], answer: 1 },
  { question: "Which country has the most sheep?", options: ["Australia", "New Zealand", "Uruguay", "Argentina"], answer: 0 },
  { question: "What is the capital of Slovakia?", options: ["Košice", "Bratislava", "Prešov", "Žilina"], answer: 1 },
  { question: "Which country is known for its ancient ruins of Pompeii?", options: ["Greece", "Italy", "Turkey", "Egypt"], answer: 1 },
  { question: "What is the capital of Myanmar?", options: ["Yangon", "Naypyidaw", "Mandalay", "Bagan"], answer: 1 },
  { question: "Which country has the most tigers?", options: ["China", "India", "Russia", "Nepal"], answer: 1 },
  { question: "What is the capital of Bolivia?", options: ["Santa Cruz", "La Paz", "Cochabamba", "Oruro"], answer: 1 },
  { question: "Which country is famous for its cherry blossoms?", options: ["China", "Japan", "Korea", "Taiwan"], answer: 1 },
  { question: "What is the capital of Paraguay?", options: ["Ciudad del Este", "Asunción", "San Lorenzo", "Luque"], answer: 1 },
  { question: "Which country has the most diamonds?", options: ["South Africa", "Botswana", "Russia", "Canada"], answer: 1 },
  { question: "What is the capital of Uruguay?", options: ["Punta del Este", "Montevideo", "Salto", "Paysandú"], answer: 1 },
  { question: "Which country is known for its Northern Lights?", options: ["Canada", "Norway", "Finland", "Iceland"], answer: 1 },
  { question: "What is the capital of Ecuador?", options: ["Guayaquil", "Quito", "Cuenca", "Ambato"], answer: 1 },
  { question: "Which country has the most oil reserves?", options: ["Saudi Arabia", "Venezuela", "Russia", "Iran"], answer: 1 },
  { question: "What is the capital of Venezuela?", options: ["Maracaibo", "Caracas", "Valencia", "Barquisimeto"], answer: 1 },
  { question: "Which country is famous for its ancient temples of Bagan?", options: ["Thailand", "Myanmar", "Cambodia", "Laos"], answer: 1 },
  { question: "What is the capital of Colombia?", options: ["Medellín", "Bogotá", "Cali", "Barranquilla"], answer: 1 },
  { question: "Which country has the most glaciers?", options: ["Canada", "Alaska", "Greenland", "Antarctica"], answer: 3 },
  { question: "What is the capital of Panama?", options: ["Colón", "Panama City", "David", "Santiago"], answer: 1 },
  { question: "Which country is known for its ancient city of Babylon?", options: ["Iran", "Iraq", "Syria", "Turkey"], answer: 1 },
  { question: "What is the capital of Costa Rica?", options: ["Cartago", "San José", "Alajuela", "Puntarenas"], answer: 1 },
  { question: "Which country has the most UNESCO Biosphere Reserves?", options: ["USA", "Spain", "Russia", "Mexico"], answer: 1 },
  { question: "What is the capital of Guatemala?", options: ["Antigua", "Guatemala City", "Quetzaltenango", "Escuintla"], answer: 1 },
  { question: "Which country is famous for its Easter Island statues?", options: ["Peru", "Chile", "Ecuador", "Bolivia"], answer: 1 },
  { question: "What is the capital of Honduras?", options: ["San Pedro Sula", "Tegucigalpa", "La Ceiba", "El Progreso"], answer: 1 },
  { question: "Which country has the most coral islands?", options: ["Philippines", "Maldives", "Indonesia", "Marshall Islands"], answer: 1 },
  { question: "What is the capital of Nicaragua?", options: ["León", "Managua", "Granada", "Masaya"], answer: 1 },
  { question: "Which country is known for its Galápagos Islands?", options: ["Peru", "Ecuador", "Colombia", "Chile"], answer: 1 },
  { question: "What is the capital of El Salvador?", options: ["Santa Ana", "San Salvador", "San Miguel", "Soyapango"], answer: 1 },
  { question: "Which country has the most active geysers?", options: ["USA", "Iceland", "Russia", "New Zealand"], answer: 1 },
  { question: "What is the capital of Belize?", options: ["Belize City", "Belmopan", "San Ignacio", "Orange Walk"], answer: 1 },
  { question: "Which country is famous for its Komodo dragons?", options: ["Philippines", "Indonesia", "Malaysia", "Thailand"], answer: 1 },
  { question: "What is the capital of Jamaica?", options: ["Montego Bay", "Kingston", "Spanish Town", "Portmore"], answer: 1 },
  { question: "Which country has the most biodiversity?", options: ["Indonesia", "Brazil", "Colombia", "Peru"], answer: 1 },
  { question: "What is the capital of Cuba?", options: ["Santiago", "Havana", "Camagüey", "Holguín"], answer: 1 },
  { question: "Which country is known for its ancient Mayan ruins?", options: ["Peru", "Mexico", "Ecuador", "Colombia"], answer: 1 },
  { question: "What is the capital of Haiti?", options: ["Cap-Haïtien", "Port-au-Prince", "Gonaïves", "Les Cayes"], answer: 1 },
  { question: "Which country has the most waterfalls?", options: ["Brazil", "Norway", "Iceland", "Venezuela"], answer: 1 },
  { question: "What is the capital of Dominican Republic?", options: ["Santiago", "Santo Domingo", "La Romana", "San Pedro de Macorís"], answer: 1 },
  { question: "Which country is famous for its giant tortoises?", options: ["Madagascar", "Galápagos Islands", "Seychelles", "Mauritius"], answer: 1 }
];

export default questions;
